import smtplib
import socket
import ssl
import logging
import markdown
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

# Force IPv4 — some environments don't support IPv6 sockets
_real_getaddrinfo = socket.getaddrinfo
def _ipv4_getaddrinfo(host, port, family=0, *args, **kwargs):
    return _real_getaddrinfo(host, port, socket.AF_INET, *args, **kwargs)
socket.getaddrinfo = _ipv4_getaddrinfo

logger = logging.getLogger(__name__)

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{subject}</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
                   'Helvetica Neue', Arial, sans-serif;
      background: #f0f4f8;
      color: #2d3748;
      line-height: 1.7;
      padding: 24px 16px;
    }}
    .wrapper {{
      max-width: 760px;
      margin: 0 auto;
    }}
    .card {{
      background: #ffffff;
      border-radius: 16px;
      box-shadow: 0 4px 24px rgba(0,0,0,0.08);
      padding: 44px 48px;
    }}
    h1 {{
      font-size: 28px;
      font-weight: 700;
      color: #1a202c;
      border-bottom: 3px solid #667eea;
      padding-bottom: 14px;
      margin-bottom: 24px;
    }}
    h2 {{
      font-size: 20px;
      font-weight: 700;
      color: #2d3748;
      margin-top: 36px;
      margin-bottom: 14px;
      padding-left: 12px;
      border-left: 4px solid #667eea;
    }}
    h3 {{
      font-size: 17px;
      font-weight: 600;
      color: #4a5568;
      margin-top: 22px;
      margin-bottom: 10px;
    }}
    p {{ margin: 10px 0; }}
    ul, ol {{
      padding-left: 22px;
      margin: 10px 0;
    }}
    li {{ margin: 6px 0; }}
    a {{ color: #667eea; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    hr {{
      border: none;
      border-top: 1px solid #e2e8f0;
      margin: 32px 0;
    }}
    strong {{ color: #1a202c; }}
    code {{
      background: #edf2f7;
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 0.9em;
    }}
    .footer {{
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e2e8f0;
      text-align: center;
      font-size: 13px;
      color: #a0aec0;
    }}
    .badge {{
      display: inline-block;
      background: #667eea;
      color: #fff;
      padding: 3px 10px;
      border-radius: 12px;
      font-size: 12px;
      font-weight: 600;
      margin-right: 4px;
    }}
    @media (max-width: 600px) {{
      .card {{ padding: 28px 20px; }}
      h1 {{ font-size: 22px; }}
    }}
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="card">
      {body}
      <div class="footer">
        <p>
          <span class="badge">AI</span>
          Generated by <strong>AI-AT-ADVENT Daily Digest</strong>
          &middot; Powered by Claude
        </p>
        <p style="margin-top: 6px;">Delivered daily at 5:00 AM ET</p>
      </div>
    </div>
  </div>
</body>
</html>
"""


def _digest_to_html(digest_markdown: str, subject: str) -> str:
    """Convert the Claude-generated markdown digest to a styled HTML email."""
    body_html = markdown.markdown(
        digest_markdown,
        extensions=["extra", "nl2br"],
    )
    return _HTML_TEMPLATE.format(subject=subject, body=body_html)


def send_email(
    digest_content: str,
    from_email: str,
    to_email: str,
    smtp_host: str,
    smtp_port: int,
    smtp_username: str,
    smtp_password: str,
    use_tls: bool = True,
) -> None:
    """Send the daily digest as a styled HTML email via SMTP."""
    date_str = datetime.now().strftime("%A, %B %d, %Y")
    subject = "TODAY's MAJOR AI NEWS"

    html_body = _digest_to_html(digest_content, subject)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_email
    msg["To"] = to_email

    # Plain-text fallback for email clients that don't render HTML
    msg.attach(MIMEText(digest_content, "plain", "utf-8"))
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    logger.info("Sending digest email to %s via %s:%d ...", to_email, smtp_host, smtp_port)

    # Try STARTTLS on port 587, then fall back to SSL on port 465
    def _try_starttls():
        with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as server:
            server.starttls()
            server.login(smtp_username, smtp_password)
            server.sendmail(from_email, [to_email], msg.as_string())

    def _try_ssl():
        ctx = ssl.create_default_context()
        with smtplib.SMTP_SSL(smtp_host, 465, context=ctx, timeout=30) as server:
            server.login(smtp_username, smtp_password)
            server.sendmail(from_email, [to_email], msg.as_string())

    try:
        _try_starttls()
        logger.info("Email sent successfully via STARTTLS.")
    except (OSError, smtplib.SMTPException) as exc:
        logger.warning("STARTTLS failed (%s), retrying with SSL port 465...", exc)
        try:
            _try_ssl()
            logger.info("Email sent successfully via SSL.")
        except smtplib.SMTPAuthenticationError as exc2:
            logger.error("SMTP auth failed — check SMTP_USERNAME / SMTP_PASSWORD: %s", exc2)
            raise
        except Exception as exc2:
            logger.error("Both SMTP methods failed: %s", exc2)
            raise
